default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Yr323112
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: furima-46197_development

test:
  <<: *default
  database: furima-46197_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>