default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Yr323112
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: furima-46197_development

test:
  <<: *default
  database: furima-46197_test

production:
  <<: *default
  adapter: mysql2
  database: furima-46197_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
  url: <%= ENV['DATABASE_URL'] %>